api/urls.py
from django.conf.urls import url, include
from rest_framework.routers import DefaultRouter
from api import views

# Create a router and register our viewsets with it.
router = DefaultRouter()
router.register(r'entities/items', views.ItemViewSet)
router.register(r'entities/properties', views.PropertyViewSet)

# The API URLs are now determined automatically by the router.
urlpatterns = [
    url(r'^', include(router.urls))
]

djangobase/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path, re_path
from django.views.generic import TemplateView

urlpatterns = [
  path('admin/', admin.site.urls),
  path('', include('home.urls')),
  path('api/v1/', include('api.urls')),
]

home/urls.py
from django.urls import path

from .views import (ClaimCreateView, ClaimUpdateView, EntityDetailView,
                    ItemCreateView, ItemUpdateView, PropertyCreateView,
                    PropertyUpdateView, SpecialPagesView)

app_name = "home"

urlpatterns = [
    path('entities/<slug:slug>/', EntityDetailView.as_view(), name='entity-detail'),
    path('entities/create-claim', ClaimCreateView.as_view(), name='claim-create'),
    path('entities/update-claim/<int:pk>', ClaimUpdateView.as_view(), name='claim-update'),
    path('entities/create-item', ItemCreateView.as_view(), name='item-create'),
    path('entities/update-item/<slug:slug>', ItemUpdateView.as_view(), name='item-update'),
    path('entities/create-property', PropertyCreateView.as_view(), name='property-create'),
    path('entities/update-property/<slug:slug>', PropertyUpdateView.as_view(), name='property-update'),
    path('special-pages', SpecialPagesView.as_view(), name='special-pages'),
]

home/models.py
import string
import uuid
from builtins import NotImplementedError, hasattr, property

from django.db import models
from django.template.defaultfilters import slugify
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _
from taggit.managers import TaggableManager

import random
from struct import pack


def random_generator(size=7, chars=string.ascii_uppercase + string.digits):
    return ''.join(random.choice(chars) for x in range(size))

def is_slug_valid(slug):
    if slug.startswith("Q") or slug.startswith("P"):
        return True
    else:
        return False

class Entity(models.Model):
    slug = models.SlugField(max_length=30, blank=True)
    label = models.CharField(max_length=30, blank=True)
    description = models.CharField(max_length=200, blank=True)
    timestamp = models.DateTimeField(auto_now=True, auto_now_add=False)
    aliases = TaggableManager(blank=True)

    def __str__(self):
        return "{}".format(self.slug)

    def get_absolute_url(self):
        return reverse('home:entity-detail', kwargs={'slug': self.slug})
    
    def get_edit_url(self):
        if hasattr(self, 'item'):
            return reverse('home:item-update', kwargs={'slug': self.slug})
        elif hasattr(self, 'property'):
            return reverse('home:property-update', kwargs={'slug': self.slug})
        else:
            raise NotImplementedError

    def get_aliases(self):
        if hasattr(self, "item"):
            return self.item.aliases.names()
        elif hasattr(self, "property"):
            return self.property.aliases.names()
        else:
            raise NotImplementedError


    class Meta:
        verbose_name_plural = "entities"

class Item(Entity):
    def save(self, *args, **kwargs):
        if not self.slug:
            if Item.objects.count() > 0:
                last_slug = int(Item.objects.last().slug[1:])
                self.slug = "Q" + str(last_slug + 1)
            else:
                self.slug = "Q1"
        super(Item, self).save(*args, **kwargs)


DATATYPE_CHOICES = (
    (1, _("item")),

    (2, _("property")),
    (3, _("string"))
)

class Property(Entity):
    value_type = models.IntegerField(choices=DATATYPE_CHOICES, default=1)

    def save(self, *args, **kwargs):
        if not self.slug:
            if Property.objects.count() > 0:
                last_slug = int(Property.objects.last().slug[1:])
                self.slug = "P" + str(last_slug + 1)
            else:
                self.slug = "P1"
        super(Property, self).save(*args, **kwargs)

    def check_value(self, value):
        if value_type == 1:
            self.check_item(value)
        elif value_type == 2:
            self.check_property(value)
        elif value_type == 3:
            self.check_string(value)

    def check_item(self, value):
        pass

    def check_property(self, value):
        pass

    def check_string(self, value):
        pass


    class Meta:
        verbose_name_plural = "properties"
            

RANK_CHOICES = (
    (1, _("Preferred")),
    (2, _("Normal")),
    (3, _("Deprecated"))
)

class Claim(models.Model):
    entity = models.ForeignKey(Entity, on_delete=models.CASCADE, related_name="claims")
    prop = models.ForeignKey(Property, on_delete=models.CASCADE, related_name="prop_claims")
    value = models.CharField(max_length=200, blank=True)
    rank = models.IntegerField(choices=RANK_CHOICES, default=2)

    def get_value(self):
        value = self.value
        DATATYPE_CHOICES_INDEX = {key: value for key, value in DATATYPE_CHOICES}

        if DATATYPE_CHOICES_INDEX[self.prop.value_type] == 'item':
            return Item.objects.get(slug=value)
        elif DATATYPE_CHOICES_INDEX[self.prop.value_type] == 'property':
            return Property.objects.get(slug=value)
        elif DATATYPE_CHOICES_INDEX[self.prop.value_type] == 'string':
            return value
        return None

    def get_value_display(self):
        result = None
        DATATYPE_CHOICES_INDEX = {key: value for key, value in DATATYPE_CHOICES}

        if DATATYPE_CHOICES_INDEX[self.prop.value_type] == 'item':
            result = Item.objects.get(slug=self.value).label
        elif DATATYPE_CHOICES_INDEX[self.prop.value_type] == 'property':
            result = Property.objects.get(slug=self.value).label
        elif DATATYPE_CHOICES_INDEX[self.prop.value_type] == 'string':
            result = self.value
        return result

    def get_value_url(self):
        result = None
        DATATYPE_CHOICES_INDEX = {key: value for key, value in DATATYPE_CHOICES}

        if DATATYPE_CHOICES_INDEX[self.prop.value_type] == 'item':
            result = Item.objects.get(slug=self.value).get_absolute_url
        elif DATATYPE_CHOICES_INDEX[self.prop.value_type] == 'property':
            result = Property.objects.get(slug=self.value).get_absolute_url
        elif DATATYPE_CHOICES_INDEX[self.prop.value_type] == 'string':
            result = None
        return result

    def get_absolute_url(self):
        return self.entity.get_absolute_url()

    def __str__(self):
        return "{} -> {}".format(self.prop.label, self.value)

home/forms.py
from django import forms

from .models import Item, Property


class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['label', 'description', 'aliases']
        labels = {
            'aliases': "Aliases"
        }
        help_texts = {
            'aliases': "A list of alternative names, separated by pipe character (|)."
        }

class PropertyForm(forms.ModelForm):
    class Meta:
        model = Property
        fields = ['label', 'description', 'value_type', 'aliases']
        labels = {
            'aliases': "Aliases"
        }
        help_texts = {
            'aliases': "A list of alternative names, separated by pipe character (|)."
        }

home/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404
from django.views.generic.detail import DetailView
from django.views.generic.edit import (CreateView, DeleteView, FormView,
                                       UpdateView)

from .forms import ItemForm, PropertyForm
from .models import Claim, Entity, Item, Property
from django.views.generic import TemplateView


class EntityDetailView(DetailView):
    model = Entity

class ClaimCreateView(CreateView):
    model = Claim
    fields = ['entity', 'prop', 'value', 'rank']

    def get_initial(self):
        initial = super(ClaimCreateView, self).get_initial()
        initial = initial.copy()
        if self.request.GET.get("slug"):
            initial['entity'] = Entity.objects.get(slug=self.request.GET.get("slug"))
        return initial

class ClaimUpdateView(UpdateView):
    model = Claim
    fields = ['value', 'rank']

class ItemCreateView(CreateView):
    model = Item
    form_class = ItemForm

class ItemUpdateView(UpdateView):
    model = Item
    form_class = ItemForm

class PropertyCreateView(CreateView):
    model = Property
    form_class = PropertyForm

class PropertyUpdateView(UpdateView):
    model = Property
    form_class = PropertyForm

class SpecialPagesView(TemplateView):
    template_name = "home/special_pages.html"

home/templates/home/base.html
{% load static %}
<!doctype html>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>{% block title %}Wikiname{% endblock %}</title>

        <meta name="description" content="The HTML5 Herald">
        <meta name="author" content="SitePoint">
        {% block meta %}
        {% endblock %}

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
        {% block css %}
        {% endblock %}
    </head>

    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'home:special-pages' %}">Special pages</a>
                    </li>
                </ul>
                <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form>
            </div>
        </nav>
        {% block content %}
        {% endblock %}

        <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
        {% block scripts %}
        {% endblock %}
    </body>
</html>

home/templates/home/claim_form.html
{% extends 'home/base.html' %}

{% block title %}Create a new claim - Wikiname{% endblock %}

{% block content %}
{% load crispy_forms_tags %}
<div class="container">
    <div class="row border-bottom">
        <div class="col">
            <h1 class="h2">Create a new claim</h1>
        </div>
    </div>

    <form method="post">{% csrf_token %}
        {{ form | crispy  }}
        <input class="btn btn-primary float-right" type="submit" value="Create claim">
    </form>
</div>
{% endblock %}

home/templates/home/entity_detail.html
{% extends 'home/base.html' %}

{% block title %}{{object.label}} - Wikiname{% endblock %}

{% block content %}
<div class="container">
    <div class="row border-bottom">
        <div class="col">
            <h1 class="h2">{{object.label}} <small class="text-muted">({{object.slug}})</small></h1>
        </div>
    </div>

    <div class="row">
        <div class="col">
            {{object.description}}
        </div>

        <div class="col-2">
            <a href="{{object.get_edit_url}}"><i class="fas fa-pencil-alt"></i> edit</a>
        </div>
    </div>

    <div class="row">
        <div class="col text-muted">
            {% for alias in object.get_aliases %}
            {{alias}} {% if forloop.last %}{% else %}|{% endif %}
            {% endfor %}
        </div>
    </div>

    {% if object.property.value_type %}
    <div class="row mt-3">
        <div class="col">
            <h2 class="h3">Data type</h2>
        </div>
    </div>

    <div class="row">
        <div class="col border border-secondary">
            {{object.property.get_value_type_display}}
        </div>
    </div>
    {% endif %}

    <div class="row mt-3">
        <div class="col">
            <h2 class="h3">Statements</h2>
        </div>
    </div>

    {% for claim in object.claim_set.all %}
    <div class="row border border-dark">
        <div class="col-2 bg-light border-secondary border-right">
            <a href="{{claim.prop.get_absolute_url}}">{{claim.prop.label}}</a>
        </div>
        <div class="col">
            {% if get_value_url %}
            <a href="{{claim.get_value_url}}">{{claim.get_value_display}}</a>
            {% else %}
            {{claim.get_value_display}}
            {% endif %}
        </div>
        <div class="col">
            <a href="{% url 'home:claim-update' claim.id %}"><i class="fas fa-pencil-alt"></i> edit</a>
        </div>
    </div>    
    {% empty %}
    {% endfor %}

    <div class="row mt-3 float-right">
        <div class="col">
            <a href="{% url 'home:claim-create' %}?slug={{object.slug}}"><i class="fas fa-plus"></i> add statement</a>
        </div>
    </div>
</div>
{% endblock %}

home/templates/home/item_form.html
{% extends 'home/base.html' %}

{% block title %}Create a new item - Wikiname{% endblock %}

{% block content %}
{% load crispy_forms_tags %}
<div class="container">
    <div class="row border-bottom">
        <div class="col">
            <h1 class="h2">Create a new item</h1>
        </div>
    </div>

    <form method="post">{% csrf_token %}
        {{ form | crispy }}
        <input class="btn btn-primary float-right" type="submit" value="Create item">
    </form>
</div>
{% endblock %}

home/templates/home/property_form.html
{% extends 'home/base.html' %}

{% block title %}Create a new property - Wikiname{% endblock %}

{% block content %}
{% load crispy_forms_tags %}
<div class="container">
    <div class="row border-bottom">
        <div class="col">
            <h1 class="h2">Create a new property</h1>
        </div>
    </div>

    <form method="post">{% csrf_token %}
        {{ form | crispy }}
        <input class="btn btn-primary float-right" type="submit" value="Create property">
    </form>
</div>
{% endblock %}

home/templates/home/special_pages.html
{% extends 'home/base.html' %}

{% block title %}Special pages - Wikiname{% endblock %}

{% block content %}
{% load crispy_forms_tags %}
<div class="container">
    <div class="row border-bottom">
        <div class="col">
            <h1 class="h2">Special pages</h1>
        </div>
    </div>

    <div class="row">
        <div class="col">            
            <ul>
                <li><a href="{% url 'home:item-create' %}">Create a new item</a></li>
                <li><a href="{% url 'home:property-create' %}">Create a new property</a></li>
            </ul>
        </div>
    </div>
</div>
{% endblock %}